export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SUCCESSFUL = 'AUTH_SUCCESSFUL';
export const AUTH_ERROR = 'AUTH_ERROR';

export const FOOD_LIST_FETCH = 'FOOD_LIST_FETCH';
export const FOOD_BANNER_LIST_FETCH = 'FOOD_BANNER_LIST_FETCH';
export const FOOD_CATEGORY_LIST_FETCH = 'FOOD_CATEGORY_LIST_FETCH';
export const FOOD_ERROR = 'FOOD_ERROR';
export const FOOD_LOADING = 'FOOD_LOADING';
